language: node_js

node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
    CC_TEST_REPORTER_ID=925b24b17acff9fcf7a6d0bf208bcb1ecdf082c0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
script:
  - npm run test

after_success:
  - npm run coveralls